url: https://www.infernalscoop.com   # with the https protocol
enforce_ssl: www.infernalscoop.com   # without any protocol

# For example, my configuration is this:
url: https://sheharyar.me
enforce_ssl: sheharyar.me
