// Generated by CoffeeScript 1.8.0
var NAV, SUBJECTS, TIMES, authedData, end_time, msnry, ref, start_time;

msnry = null;

ref = new Firebase("https://question-everything.firebaseio.com");

NAV = {
  'home': 'home',
  'faq': 'faq',
  'exp': 'what is this',
  'graph': 'view graph'
};

SUBJECTS = {
  'fun': 'Fun',
  'serious': 'Serious',
  'stories': 'Stories',
  'test': 'testing'
};

TIMES = {
  'hour': 'past hour',
  'day': 'past 24 hours',
  'year': 'past year',
  'all': 'all time'
};

authedData = null;

start_time = 0;

end_time = Date.now();

ref.authAnonymously(function(err, data) {
  var renderHeader, renderLoginPopup, renderQuestion;
  renderHeader = function() {
    var $header, nav_selected, subject_selected, times_selected;
    $header = $('body > .container > .header');
    nav_selected = 'home';
    subject_selected = 'test';
    times_selected = 'all';
    $header.html(teacup.render(function() {
      div('.nav', function() {
        var key, val, _results;
        _results = [];
        for (key in NAV) {
          val = NAV[key];
          _results.push(div('.nav-item', {
            'data': {
              'nav': key,
              'selected': "" + (key === nav_selected)
            }
          }, function() {
            return val;
          }));
        }
        return _results;
      });
      div('.subjects', function() {
        var key, val, _results;
        _results = [];
        for (key in SUBJECTS) {
          val = SUBJECTS[key];
          _results.push(div('.subject', {
            'data': {
              subject: key,
              selected: "" + (key === subject_selected)
            }
          }, function() {
            return val;
          }));
        }
        return _results;
      });
      return div('.times', function() {
        var key, val, _results;
        _results = [];
        for (key in TIMES) {
          val = TIMES[key];
          _results.push(div('.time', {
            'data': {
              time: key,
              selected: "" + (key === times_selected)
            }
          }, function() {
            return val;
          }));
        }
        return _results;
      });
    }));
    $header.find('.nav-item').on('click', function(e) {
      var $el;
      $el = $(e.currentTarget);
      $el.siblings().attr('data-selected', false);
      return $el.attr('data-selected', true);
    });
    $header.find('.subjects .subject').on('click', function(e) {
      var $el;
      $el = $(e.currentTarget);
      $el.siblings().attr('data-selected', false);
      $el.attr('data-selected', true);
      return renderQuestion($el.data('subject'));
    });
    return $header.find('.time').on('click', function(e) {
      var $el, $questions;
      $el = $(e.currentTarget);
      $el.siblings().attr('data-selected', false);
      $el.attr('data-selected', true);
      $questions = $('body .questions');
      return renderQuestion($questions.data('link'), $questions.data('previous'));
    });
  };
  renderLoginPopup = function() {};
  renderQuestion = function(link, previous) {
    var $questions, getNextQ, time;
    if (link == null) {
      link = "test";
    }
    if (previous == null) {
      previous = false;
    }
    time = $('body > .container > .header .time[data-selected=true]').data('time') || 'all';
    switch (time) {
      case 'hour':
        start_time = Date.now() - 60 * 60 * 1000;
        break;
      case 'day':
        start_time = Date.now() - 24 * 60 * 60 * 1000;
        break;
      case 'year':
        start_time = Date.now() - 365 * 24 * 60 * 60 * 1000;
        break;
      case 'all':
        start_time = 0;
    }
    getNextQ = function(finish) {
      if (link) {
        return ref.child(link).orderByChild('created').startAt(start_time).endAt(Date.now()).once('value', function(doc) {
          var items, key, new_items, val;
          items = doc.val() || {};
          new_items = [];
          for (key in items) {
            val = items[key];
            val.key = key;
            new_items.push(val);
          }
          new_items = new_items.sort(function(a, b) {
            return b.vote - a.vote;
          });
          return finish(new_items);
        });
      } else {
        return finish(null);
      }
    };
    $('body .questions-container').html(teacup.render(function() {
      return div('.questions');
    }));
    $questions = $('body .questions');
    $questions.attr('data-link', link);
    $questions.attr('data-previous', previous);
    $(window).off('resize', function() {});
    $(window).on('resize', function() {
      var width;
      width = Math.floor($(window).width() / 340);
      return $('.questions-container').css('max-width', "" + (width * 340) + "px");
    });
    return getNextQ(function(new_items) {
      var $new_question;
      if (new_items != null ? new_items.length : void 0) {
        new_items.forEach(function(child_item) {
          var $question, item, key, question, title, vote, _ref;
          _ref = child_item || {}, question = _ref.question, vote = _ref.vote, title = _ref.title, key = _ref.key;
          if (!(question && title)) {
            return false;
          }
          item = localStorage.getItem(key) || {};
          $question = $(teacup.render(function() {
            return div('.question', {
              'data-key': key
            }, function() {
              var flag;
              div('.voting', function() {
                div({
                  'data-arrow': 'up'
                });
                div(".vote", function() {});
                return div({
                  'data-arrow': 'down'
                });
              });
              div('.question-title', function() {
                return title;
              });
              div('.question-body', function() {
                return question;
              });
              flag = true;
              div('.answers', function() {
                var ans, opt, _i, _results;
                _results = [];
                for (opt = _i = 1; _i <= 4; opt = ++_i) {
                  ans = child_item["answer_" + opt];
                  if (!ans) {
                    continue;
                  }
                  div(function() {
                    return span('.text', {
                      data: {
                        answer: "answer_" + opt,
                        next: ans.next
                      }
                    }, function() {
                      return ans.text;
                    });
                  });
                  _results.push(flag = flag && ans.next);
                }
                return _results;
              });
              if (!flag) {
                return div('.asterisk', function() {
                  return 'dead end';
                });
              }
            });
          }));
          $questions.append($question);
          return (function($question) {
            $question.find('[data-arrow]').on('click', function(e) {
              var $el, incriment, modified_incriment;
              $el = $(e.currentTarget);
              incriment = $el.data('arrow') === 'up' ? 1 : -1;
              item = JSON.parse(localStorage.getItem(key) || '{}');
              modified_incriment = incriment;
              if (item.vote === incriment) {
                modified_incriment = incriment * -1;
                incriment = 0;
              } else if (item.vote === incriment * -1) {
                modified_incriment = incriment * 2;
              }
              item.vote = incriment;
              item.vote_inverse = incriment * -1;
              localStorage.setItem(key, JSON.stringify(item));
              return ref.child("" + link + "/" + key + "/vote").once('value', function(current_vote_doc) {
                var currentVote, new_val;
                currentVote = (current_vote_doc != null ? current_vote_doc.val() : void 0) || 0;
                new_val = currentVote + modified_incriment;
                ref.child("" + link + "/" + key + "/vote").set(new_val);
                return ref.child("" + link + "/" + key + "/vote_inverse").set(new_val * -1);
              });
            });
            ref.child("" + link + "/" + key + "/vote").on('value', function(vote_doc) {
              var $vote, local_vote, new_vote;
              new_vote = (vote_doc != null ? vote_doc.val() : void 0) || 0;
              $vote = $question.find('.vote');
              $vote.html("" + new_vote);
              $vote.toggleClass('bad', new_vote < 0);
              $vote.toggleClass('good', new_vote > 5);
              item = JSON.parse(localStorage.getItem(key) || '{}');
              local_vote = 'none';
              if (item.vote > 0) {
                local_vote = 'up';
              } else if (item.vote < 0) {
                local_vote = 'down';
              }
              return $question.attr('data-vote', local_vote);
            });
            $question.find('.answers .text').on('click', function(e) {
              var $el, key_previous, next;
              $el = $(e.currentTarget);
              next = $el.data('next');
              key = $el.closest('.question').data('key');
              key_previous = "" + link + "/" + key + "/" + ($el.data('answer'));
              ref.child("" + key_previous + "/count").transaction(function(currentCount) {
                if (currentCount == null) {
                  currentCount = 0;
                }
                return currentCount + 1;
              });
              return renderQuestion(next, key_previous);
            });
            return false;
          })($question);
        });
      }
      $new_question = $(teacup.render(function() {
        return div('.question', function() {
          div('.open-pop', function() {
            if (previous) {
              return 'add branch at this point';
            } else {
              return 'Create new story';
            }
          });
          return div('.modalDialog', function() {
            return div('.new-question', function() {
              h3(function() {
                return 'Submitting a new Post';
              });
              span({
                "class": 'close'
              }, function() {
                return 'X';
              });
              return form(function() {
                div('.text-area-container', function() {
                  textarea('.question-title', {
                    'data-maxlength': 120,
                    placeholder: "Add title",
                    required: true
                  });
                  div('.resizer question-body', function() {
                    return 'A';
                  });
                  return div('.characters', function() {
                    return '';
                  });
                });
                div('.text-area-container', function() {
                  textarea('.question-body', {
                    'data-maxlength': 250,
                    placeholder: "Add your body",
                    required: true
                  });
                  div('.resizer question-body', function() {
                    return 'A';
                  });
                  return div('.characters', function() {
                    return '';
                  });
                });
                div('.answers', function() {
                  var opt, _i, _results;
                  _results = [];
                  for (opt = _i = 1; _i <= 4; opt = ++_i) {
                    _results.push(div('.text-area-container', function() {
                      var placeholder, required;
                      required = opt === 1;
                      placeholder = required ? 'Put choice here' : 'Put (optional) choice here';
                      textarea(".answer_" + opt, {
                        'data-maxlength': 140,
                        placeholder: placeholder,
                        required: required
                      });
                      div('.resizer', function() {
                        return 'A';
                      });
                      return div('.characters', function() {
                        return '';
                      });
                    }));
                  }
                  return _results;
                });
                return input({
                  type: 'submit',
                  value: 'submit'
                });
              });
            });
          });
        });
      }));
      (function($new_question) {
        $questions.prepend($new_question);
        console.log($new_question.find('.open-pop, .close'));
        $new_question.find('.open-pop, .close').on('click', function() {
          return $new_question.find('.modalDialog').toggleClass('visible');
        });
        $new_question.find('textarea').on('input', function(e) {
          var $el, maxlength, str;
          $el = $(e.currentTarget);
          maxlength = $el.attr('data-maxlength');
          str = $el.val().slice(0, maxlength);
          $el.val(str);
          if (str.length === 0) {
            $el.next().html("");
            $el.siblings('.characters').html('');
          } else {
            $el.next().html("" + str + "\n\n");
            $el.siblings('.characters').html(maxlength - str.length);
          }
          return false;
        });
        return $new_question.find('form').on('submit', function(e) {
          var $el, answer, c, new_q, new_q_obj, opt, _i;
          if (!link) {
            link = "leaf/" + (ref.child('leaf').push().key());
          }
          $el = $(e.currentTarget);
          new_q = ref.child(link).push();
          new_q_obj = {
            answer_1: {
              text: $el.find('textarea.answer_1').val()
            },
            question: $el.find('textarea.question-body').val(),
            title: $el.find('textarea.question-title').val(),
            created: Firebase.ServerValue.TIMESTAMP,
            vote: 0,
            vote_inverse: 0
          };
          c = 2;
          for (opt = _i = 2; _i <= 4; opt = ++_i) {
            answer = $el.find("textarea.answer_" + opt).val();
            if (!answer) {
              continue;
            }
            new_q_obj["answer_" + c] = {
              text: answer
            };
            c++;
          }
          new_q.set(new_q_obj, function() {
            var question_location;
            if (!previous) {
              return renderQuestion(link, previous);
            }
            question_location = "" + link + "/" + (new_q.key());
            return ref.child("" + previous + "/next").set(link, function() {
              debugger;
              return renderQuestion(link, previous);
            });
          });
          return false;
        });
      })($new_question);
      $('.questions').masonry({
        itemSelector: '.question',
        layoutPriorities: {
          upperPosition: 1,
          shelfOrder: 1
        }
      });
      msnry = $('.questions').data('masonry');
      return $(window).trigger('resize');
    });
  };
  renderHeader();
  return renderQuestion('test');
});
